### ISSUE TITLE
Implement Back-End on New CMS

### ISSUE THREAD

**Issue by AdrielAmoguis** [dlsudatasci/dlsudatasci.github.io#15]
# Remaining TODOs
1. Fix the issue with publications entries causing a NetlifyCMS crash.
2. ~~Add the individual `program` collection (not to be confused with the `programs` collection).~~
3. Test entry creation and deletion for all collections.

**Comment by unissechua** [comment]
Hi @AdrielAmoguis - can we just keep this issue open and see if you can start first with the Jekyll template fix so that we can verify if the issue will be fixed?

**Comment by AdrielAmoguis** [comment]
Hello Ms. @unissechua! This is understood. I shall investigate the template now for possible breaking points. Additionally, when can I expect the final mockup for the updated design?
