### ISSUE TITLE
NetlifyCMS Requires Organization OAuth Permissions

### ISSUE THREAD

**Issue by AdrielAmoguis** [dlsudatasci/dlsudatasci.github.io#19]
Netlify CMS requires the OAuth permissions of the `dlsudatasci` Github organization to commit to the `dlsudatasci.github.io` repository on the behalf of the user. Though some existing articles still need to be converted to the expected NetlifyCMS markdown format, the admin panel is already installed. Changes were applied in the `netlify-cms-integration` branch.

<img width="387" alt="image" src="https://user-images.githubusercontent.com/60635460/213974748-3f80c2fc-9c5c-4dd5-9aba-0ff7009eaac9.png">

**Comment by unissechua** [comment]
Did Netlify CMS request for permissions? I don't see an approval request.

**Comment by AdrielAmoguis** [comment]
Removing the restrictions solved the issue, but this might have an unwanted effect in terms of security in the GitHub Organization. I shall keep this issue open until we either find the setting to give authorization just to Netlify without disabling all restrictions altogether or if we conclude that this is the only way to address the issue.
