### ISSUE TITLE
Directory structure of the proposed website content

### ISSUE THREAD

**Issue by unissechua** [dlsudatasci/dlsudatasci.github.io#2]
Update the README.md of the project or comment here in this issue the proposed pages needed for the official website.

**Comment by mocordel** [comment]
**People:**
- Steering Committee
- Faculty Affiliates (me, unisse, briane, sash, jude, gaddiel, the big data analytics team --- myk, fritz etc.)
- Student Affiliates (COMET (thesis) students working with DS projects)

**Research:**
- Projects
     - Once approved: title of the project funded by AKI
     - Project mo Unisse
- Publications

**Academic Programs**
- Minor in Data Science (details here: https://www.dlsu.edu.ph/minor/)
- MS in Data Science (details here: https://docs.google.com/document/d/1yaXZn-uZkcekKYfLii0p8MwaIlwWCNm9ZtKDLXGxvHA/edit?usp=sharing)

**Short courses:**
- Foundations of Data Science
          - Description (e.g. info in FB)
          - Offered month (every T1 (January) and T2 (May) -- add subject to change)
- Data Visualization
          - Description (e.g. info in FB)
          - Offered month (every T3 (August) -- add subject to change)
- Big Data Analytics
          - Description (e.g. info in FB)
          - Offered month (every T1 (October) -- add subject to change)
- Machine Learning
          - Description (e.g. info in FB)
          - Offered month (every T2 (June) -- add subject to change)

**Comment by AdrielAmoguis** [comment]
Closing as archive.
